import { Inter } from 'next/font/google'
import './globals.css'
import {Toaster} from 'react-hot-toast'
import Provider from '@/context/Provider'
import { auth } from '@/auth'
import Navbar from './Components/NavBar'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Learn Next JS',
  description: 'Generated by create next app',
}

export default  async function RootLayout({ children }) {
  const session=await auth();

  return (
    <html lang="en">
      <Provider session={session}>
      <body className={inter.className}>
      <Navbar  />
        {children}
      <Toaster position='top-center' />
      
      </body>
      </Provider>
    </html>
  )
}
